name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        # Handle asyncio dependency - it's a part of stdlib in Python 3.8+
        if [ "${{ matrix.python-version }}" != "3.8" ] && [ "${{ matrix.python-version }}" != "3.9" ] && [ "${{ matrix.python-version }}" != "3.10" ] && [ "${{ matrix.python-version }}" != "3.11" ]; then
          pip install asyncio>=3.4.3
        fi
        # Install requirements with compatibility fixes
        pip install --no-deps substack_api>=0.1.0
        pip install markdownify>=0.11.6 requests>=2.28.0 tqdm>=4.64.0
        pip install python-dotenv>=0.20.0 selenium>=4.10.0 
        pip install beautifulsoup4>=4.10.0 aiohttp>=3.8.0 multiprocessing-logging>=0.3.1
        pip install lxml>=4.9.0 bs4>=0.0.1 certifi>=2023.7.22
        pip install charset-normalizer>=3.2.0 idna>=3.4 markdown>=3.4.4
        pip install soupsieve>=2.5 urllib3>=2.0.4 sqlalchemy>=2.0.20
        # Install pyppeteer conditionally - known to have version conflicts
        if [ "${{ matrix.python-version }}" == "3.8" ]; then
          pip install pyppeteer==1.0.2
        else
          pip install pyppeteer>=1.0.2
        fi
    - name: Run tests
      run: |
        pytest --cov=src tests/
