name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04  # Using a more stable Ubuntu version
    timeout-minutes: 10    # Adding timeout to prevent hanging jobs
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']  # Limiting to most current versions
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Enable caching of pip dependencies
    
    - name: Install base testing dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest pytest-cov pytest-asyncio
    
    - name: Install dependencies
      run: |
        # Install requirements from requirements.txt
        pip install -r requirements.txt
        
        # Install the rest of the dependencies
        pip install -U multiprocessing-logging bs4 certifi charset-normalizer
        pip install -U idna markdown soupsieve urllib3 sqlalchemy redis
        
        # Install asyncio explicitly and ensure pytest-asyncio is installed
        pip install -U asyncio pytest-asyncio
        
        # Handle the problematic dependencies
        pip install pyppeteer --no-dependencies
        pip install substack_api --no-dependencies
        
        # Check the installed packages
        pip list
    
    - name: Set up for tests
      run: |
        # Make sure our compatibility file is on Python's path
        export PYTHONPATH=$PYTHONPATH:$(pwd)
    
    - name: Run tests
      run: |
        # Run full tests with the compatibility layer
        python -m pytest --cov=src tests/ --cov-report=xml
