name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04  # Using a more stable Ubuntu version
    timeout-minutes: 10    # Adding timeout to prevent hanging jobs
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']  # Limiting to most current versions
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Enable caching of pip dependencies
    
    - name: Install base testing dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest pytest-cov pytest-asyncio
    
    - name: Install dependencies
      run: |
        # Skip requirements.txt and install dependencies directly with compatible versions
        
        # Core dependencies with specific versions to avoid conflicts
        pip install urllib3==1.26.18  # Older version compatible with selenium and requests
        pip install requests==2.28.2
        pip install selenium==4.1.5
        
        # Basic dependencies needed for the project
        pip install markdownify==0.11.6
        pip install tqdm==4.65.0
        pip install python-dotenv==0.21.1
        pip install beautifulsoup4==4.12.2
        pip install bs4==0.0.1
        
        # Handle async support
        pip install asyncio==3.4.3
        pip install aiohttp==3.8.5
        pip install aiosignal==1.3.1
        pip install async-timeout==4.0.3
        
        # Additional dependencies
        pip install multiprocessing-logging==0.3.4
        pip install lxml==4.9.3
        pip install attrs==23.1.0
        pip install certifi==2023.7.22
        pip install charset-normalizer==3.2.0
        pip install frozenlist==1.3.3
        pip install idna==3.4
        pip install markdown==3.4.4
        pip install multidict==6.0.4
        pip install soupsieve==2.5
        pip install yarl==1.9.2
        pip install redis==4.6.0
        pip install sqlalchemy==2.0.20
        
        # Testing dependencies
        pip install pytest-asyncio==0.21.1
        pip install pytest-cov==4.1.0
        
        # Handle problematic dependencies with minimal installation
        pip install --no-deps pyppeteer==1.0.2
        pip install --no-deps substack_api==0.1.0
        
        # Check the installed packages
        pip list
    
    - name: Set up for tests
      run: |
        # Make sure our compatibility file is on Python's path
        export PYTHONPATH=$PYTHONPATH:$(pwd)
    
    - name: Run tests
      run: |
        # Run full tests with the compatibility layer
        python -m pytest --cov=src tests/ --cov-report=xml
